'use strict'

const INTERVALS_DAILY = 'DAILY'
const INTERVALS_WEEKLY = 'WEEKLY'
const INTERVALS_MONTHLY = 'MONTHLY'
const INTERVALS_YEARLY = 'YEARLY'

module.exports = {
        INTERVALS_DAILY,
        INTERVALS_WEEKLY,
        INTERVALS_MONTHLY,
        INTERVALS_YEARLY,
}